### ISSUE TITLE
Not on npm

### ISSUE THREAD

**Issue by yocontra** [usefulthink/nodecopter-monitor#1]
Not published - getting a 404 when trying `npm install nodecopter-monitor`

**Comment by usefulthink** [comment]
umm… that's right :)
I did not publish it to npm yet, since the code should receive a lot of refactoring before.

However, you can install it using the repository-tarball from github:

```
npm install https://github.com/usefulthink/nodecopter-monitor/tarball/master
```

I leave this ticket open a a reminder to publish it soon

**Comment by usefulthink** [comment]
Ah, i see your point, the README says differntly...

Just typed `npm publish`, so it should be there soon.

**Comment by bkw** [comment]
Anyone interested in extracting the unique features of our nodecopter projects into modules that can serve as building blocks for individual nodecopter cockpits? For example - I'd like to build a cockpit using the keyboard controls of one project, the video stream of another, a little window with the drone model, auto-snapshot of recognized faces from the next project, and maybe a button to activate torrero-mode. We would have to agree on some common infrastructure though. I do NOT want to create a framework. Comments?

**Comment by usefulthink** [comment]
i've been thinking about this as well.
What I was about to do was to extract my gamepad-API-controls for instance into a seperate node-module.
In order to let others integrate this into their projects, i would need a client-instance i can send commands to and a http-server that i can attach to.

The common infrastructure you mentioned would therefore need to be something most people will agree on anyway, which is of course the node-ar-drone client, when a browser is involved a http-server and probably – this might get a bit more complicated – some sort of websocket-implementation for communication with the browser.

My proposal would be that any conforming module should be written in a way that it is able to re-use required infrastructure-components from the application. Only if the application doesn't provide these components, they are created by the module itself.

**Comment by usefulthink** [comment]
but: we should take the discussion to somewhere else :)

**Comment by bkw** [comment]
+1
Later

**Comment by usefulthink** [comment]
@bkw have a look at this: https://github.com/usefulthink/nodecopter-monitor/tree/extract-gamepad-module/lib/nodecopter-gamepad

is this something you can relate to?

**Comment by bkw** [comment]
+1 for taking the initiative!
I'm sick right now and find it very hard to concentrate, I promise to look at it in detail later!
btw: Berlin.js on Nov 15? @felixge said he'd try to make it as well.

**Comment by yocontra** [comment]
@bkw - I've got some misc. controls/utils in  https://github.com/Contra/drone for writing videos to disk, doing face recognition, turning the PNGs into canvas and drawing on them, stdin controls, etc. it might be semi-useful for it

**Comment by usefulthink** [comment]
alright, i spent a little bit of time on implementing what i think would be an approach to create "nodecopter-modules" with as little presumptions on the environment as possible and no shared infrastructure (like webserver, websocket, etc.).

I ended up with the `EventEmitter` as single required interface. The embedding library just has to make sure that events emitted in the browser are somehow sent to the server and into the gamepad-module (be it socket.io or whatever).

The new module can be found at https://github.com/usefulthink/nodecopter-gamepad - til now only the server-part is complete, i'll continue working on the client and integration-part soon.

@bkw i'm not from berlin, but let me see what i can do. berlin.js always sounds interesting.

@Contra could you imagine adapting this kind of approach for a `nodecopter-recorder`-module (i.e. simply build a module that gets signaled via events when to start/stop recording and attaches to an existing nodecopter-client)?

**Comment by usefulthink** [comment]
Ah, yes and let's continue the discussion somewhere else :)
